# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
# ░██╗░░░░░░█████╗░░██████╗░░░███████╗██╗██╗░░██╗███████╗██████╗░░
# ░██║░░░░░██╔══██╗██╔════╝░░░██╔════╝██║╚██╗██╔╝██╔════╝██╔══██╗░
# ░██║░░░░░███████║██║░░██╗░░░█████╗░░██║░╚███╔╝░█████╗░░██████╔╝░
# ░██║░░░░░██╔══██║██║░░╚██╗░░██╔══╝░░██║░██╔██╗░██╔══╝░░██╔══██╗░
# ░███████╗██║░░██║╚██████╔╝░░██║░░░░░██║██╔╝╚██╗███████╗██║░░██║░
# ░╚══════╝╚═╝░░╚═╝░╚═════╝░░░╚═╝░░░░░╚═╝╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝░
# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
# Для настройки модулей открой /plugins/LagFixer/modules/<module>.yml

# Часть настроек требует перезапуска сервера или перезагрузки плагина.
main:
  prefix: '&8[&c&l⚡&8] '
  # Показывает версию LagFixer при наведении.
  prefix_hover: true

  monitor:
    # Мониторинг TPS, MSPT, CPU и других метрик.
    resource:
      enabled: true
      # Интервал обновления в секундах
      interval: 10

    # Подсчёт сущностей и чанков.
    worlds:
      enabled: true
      # Интервал обновления в секундах
      interval: 30

    # Карта нагрузки сервера (/lagfixer map)
    map:
      enabled: false
      # Интервал обновления в секундах
      interval: 10
      id: 1

  # Автоматически отправляет ошибки LagFixer и Spark-профили разработчикам.
  errors_reporter: false
  # Автоматически проверяет обновления и уведомляет консоль и игроков с правами.
  updater: false
  # Показывает предупреждения о устаревших методах без поддержки.
  warnings: true
  # Статистика bStats: https://bstats.org/plugin/bukkit/LagFixer/19292.
  bStats: false

  command:
    permission: lagfixer.command
    aliases:
    - lf
    - antilag
    - lag
